# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\paobe\Documents\proyecto_progra_2\Empleados.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Empleados(object):
    def setupUi(self, Empleados):
        Empleados.setObjectName("Empleados")
        Empleados.resize(628, 509)
        Empleados.setMaximumSize(QtCore.QSize(628, 509))
        Empleados.setStyleSheet("background-image: url(:/fondo/imagen-llamativa-cintas-sobre-fondo-oscuro-generacion-ai_724548-22165.jpg);")
        self.tblEmpleados = QtWidgets.QTableView(Empleados)
        self.tblEmpleados.setGeometry(QtCore.QRect(160, 10, 461, 401))
        self.tblEmpleados.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblEmpleados.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblEmpleados.setObjectName("tblEmpleados")
        self.verticalLayoutWidget = QtWidgets.QWidget(Empleados)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 141, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tablaEditable = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tablaEditable.setContentsMargins(0, 0, 0, 0)
        self.tablaEditable.setObjectName("tablaEditable")
        self.lblCed = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCed.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblCed.setObjectName("lblCed")
        self.tablaEditable.addWidget(self.lblCed, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txtCed = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtCed.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtCed.setObjectName("txtCed")
        self.tablaEditable.addWidget(self.txtCed)
        self.lblNombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblNombre.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblNombre.setObjectName("lblNombre")
        self.tablaEditable.addWidget(self.lblNombre, 0, QtCore.Qt.AlignLeft)
        self.txtNombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtNombre.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtNombre.setObjectName("txtNombre")
        self.tablaEditable.addWidget(self.txtNombre, 0, QtCore.Qt.AlignRight)
        self.lblApellidos = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblApellidos.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblApellidos.setObjectName("lblApellidos")
        self.tablaEditable.addWidget(self.lblApellidos, 0, QtCore.Qt.AlignLeft)
        self.txtApellidos = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtApellidos.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"\n"
"")
        self.txtApellidos.setObjectName("txtApellidos")
        self.tablaEditable.addWidget(self.txtApellidos, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.lblTelefono = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblTelefono.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblTelefono.setObjectName("lblTelefono")
        self.tablaEditable.addWidget(self.lblTelefono, 0, QtCore.Qt.AlignLeft)
        self.txtTelefono = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtTelefono.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtTelefono.setObjectName("txtTelefono")
        self.tablaEditable.addWidget(self.txtTelefono, 0, QtCore.Qt.AlignRight)
        self.lblDireccion = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblDireccion.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblDireccion.setObjectName("lblDireccion")
        self.tablaEditable.addWidget(self.lblDireccion, 0, QtCore.Qt.AlignLeft)
        self.txtDireccion = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtDireccion.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtDireccion.setObjectName("txtDireccion")
        self.tablaEditable.addWidget(self.txtDireccion, 0, QtCore.Qt.AlignRight)
        self.lblPuesto = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblPuesto.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblPuesto.setObjectName("lblPuesto")
        self.tablaEditable.addWidget(self.lblPuesto, 0, QtCore.Qt.AlignLeft)
        self.txtPuesto = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtPuesto.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtPuesto.setObjectName("txtPuesto")
        self.tablaEditable.addWidget(self.txtPuesto, 0, QtCore.Qt.AlignRight)
        self.lblFecha = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblFecha.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblFecha.setObjectName("lblFecha")
        self.tablaEditable.addWidget(self.lblFecha, 0, QtCore.Qt.AlignLeft)
        self.txtFecha = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtFecha.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtFecha.setObjectName("txtFecha")
        self.tablaEditable.addWidget(self.txtFecha, 0, QtCore.Qt.AlignRight)
        self.lblJefatura = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblJefatura.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblJefatura.setObjectName("lblJefatura")
        self.tablaEditable.addWidget(self.lblJefatura, 0, QtCore.Qt.AlignLeft)
        self.txtJefatura = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtJefatura.setEnabled(True)
        self.txtJefatura.setMaximumSize(QtCore.QSize(134, 16777215))
        self.txtJefatura.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtJefatura.setObjectName("txtJefatura")
        self.tablaEditable.addWidget(self.txtJefatura, 0, QtCore.Qt.AlignRight)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Empleados)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(360, 420, 161, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnEliminar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnEliminar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}")
        self.btnEliminar.setObjectName("btnEliminar")
        self.verticalLayout_2.addWidget(self.btnEliminar)
        self.btnCancelar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout_2.addWidget(self.btnCancelar)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Empleados)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(170, 420, 161, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnAgregar = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnAgregar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}")
        self.btnAgregar.setObjectName("btnAgregar")
        self.verticalLayout_3.addWidget(self.btnAgregar)
        self.btnEditar = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnEditar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}")
        self.btnEditar.setObjectName("btnEditar")
        self.verticalLayout_3.addWidget(self.btnEditar)

        self.retranslateUi(Empleados)
        QtCore.QMetaObject.connectSlotsByName(Empleados)

    def retranslateUi(self, Empleados):
        _translate = QtCore.QCoreApplication.translate
        Empleados.setWindowTitle(_translate("Empleados", "Form"))
        self.lblCed.setText(_translate("Empleados", "Cedula"))
        self.lblNombre.setText(_translate("Empleados", "Nombre"))
        self.lblApellidos.setText(_translate("Empleados", "Apellidos"))
        self.lblTelefono.setText(_translate("Empleados", "Telefono"))
        self.lblDireccion.setText(_translate("Empleados", "Direccion"))
        self.lblPuesto.setText(_translate("Empleados", "Puesto"))
        self.lblFecha.setText(_translate("Empleados", "Fecha ingreso"))
        self.lblJefatura.setText(_translate("Empleados", "Jefatura SI // NO"))
        self.btnEliminar.setText(_translate("Empleados", "Eliminar"))
        self.btnCancelar.setText(_translate("Empleados", "Cancelar"))
        self.btnAgregar.setText(_translate("Empleados", "Agregar"))
        self.btnEditar.setText(_translate("Empleados", "Editar"))
import image_rc
