# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\paobe\OneDrive\Documentos\proyecto progra 2\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(447, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-image: url(:/fondo/imagen-llamativa-cintas-sobre-fondo-oscuro-generacion-ai_724548-22165.jpg);\n"
"    \n"
"border-radius:10px;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(400, 600))
        self.frame_3.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}\n"
"\n"
"QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"\n"
"QCheckBox{\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"width:18px;\n"
"height:18px;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit.setStyleSheet("image: url(:/prefijoNuevo/perfil-del-usuario.png);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lineEdit_2.setStyleSheet("image: url(:/prefijoNuevo/cerrar-con-llave.png);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 35))
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.frame_3)
        spacerItem7 = QtWidgets.QSpacerItem(104, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Iniciar Aplicacion"))
        self.checkBox.setText(_translate("MainWindow", "Recordar Contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar Sesion"))
import image_rc
