# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\paobe\Documents\proyecto_progra_2\MenuPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuPrincipal(object):
    def setupUi(self, MenuPrincipal):
        MenuPrincipal.setObjectName("MenuPrincipal")
        MenuPrincipal.resize(847, 578)
        MenuPrincipal.setStyleSheet("\n"
"background-color: rgb(139, 69, 0);")
        self.centralwidget = QtWidgets.QWidget(MenuPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.frmControles = QtWidgets.QFrame(self.centralwidget)
        self.frmControles.setGeometry(QtCore.QRect(10, 10, 191, 551))
        self.frmControles.setStyleSheet("QPushButton{\n"
"    \n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"#frmControles{\n"
"    background-image: url(:/fondo/imagen-llamativa-cintas-sobre-fondo-oscuro-generacion-ai_724548-22165.jpg);\n"
"}")
        self.frmControles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmControles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmControles.setObjectName("frmControles")
        self.btnUsuarios = QtWidgets.QPushButton(self.frmControles)
        self.btnUsuarios.setGeometry(QtCore.QRect(20, 30, 141, 41))
        self.btnUsuarios.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 85, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefijoNuevo/perfil-del-usuario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUsuarios.setIcon(icon)
        self.btnUsuarios.setObjectName("btnUsuarios")
        self.btnEmpleados = QtWidgets.QPushButton(self.frmControles)
        self.btnEmpleados.setGeometry(QtCore.QRect(20, 90, 141, 51))
        self.btnEmpleados.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 85, 0);")
        self.btnEmpleados.setIcon(icon)
        self.btnEmpleados.setObjectName("btnEmpleados")
        self.btnDepartamentos = QtWidgets.QPushButton(self.frmControles)
        self.btnDepartamentos.setGeometry(QtCore.QRect(20, 160, 141, 41))
        self.btnDepartamentos.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btnDepartamentos.setIcon(icon)
        self.btnDepartamentos.setObjectName("btnDepartamentos")
        self.btnBienes = QtWidgets.QPushButton(self.frmControles)
        self.btnBienes.setGeometry(QtCore.QRect(20, 220, 141, 41))
        self.btnBienes.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.btnBienes.setIcon(icon)
        self.btnBienes.setObjectName("btnBienes")
        self.btnAsignacion = QtWidgets.QPushButton(self.frmControles)
        self.btnAsignacion.setGeometry(QtCore.QRect(20, 280, 141, 41))
        self.btnAsignacion.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 85, 0);")
        self.btnAsignacion.setIcon(icon)
        self.btnAsignacion.setObjectName("btnAsignacion")
        self.btnAlmacenamiento = QtWidgets.QPushButton(self.frmControles)
        self.btnAlmacenamiento.setGeometry(QtCore.QRect(20, 462, 141, 41))
        self.btnAlmacenamiento.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prefijoNuevo/cerrar-con-llave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlmacenamiento.setIcon(icon1)
        self.btnAlmacenamiento.setObjectName("btnAlmacenamiento")
        self.btnReportes = QtWidgets.QPushButton(self.frmControles)
        self.btnReportes.setGeometry(QtCore.QRect(20, 400, 141, 41))
        self.btnReportes.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.btnReportes.setIcon(icon1)
        self.btnReportes.setObjectName("btnReportes")
        self.btnDesligar = QtWidgets.QPushButton(self.frmControles)
        self.btnDesligar.setGeometry(QtCore.QRect(20, 342, 141, 41))
        self.btnDesligar.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.btnDesligar.setIcon(icon)
        self.btnDesligar.setObjectName("btnDesligar")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(210, 20, 621, 541))
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        MenuPrincipal.setCentralWidget(self.centralwidget)
        self.mniUsuarios = QtWidgets.QAction(MenuPrincipal)
        self.mniUsuarios.setCheckable(True)
        self.mniUsuarios.setObjectName("mniUsuarios")
        self.mniEmpleados = QtWidgets.QAction(MenuPrincipal)
        self.mniEmpleados.setCheckable(True)
        self.mniEmpleados.setObjectName("mniEmpleados")

        self.retranslateUi(MenuPrincipal)
        self.btnUsuarios.clicked.connect(self.mdiArea.showFullScreen) # type: ignore
        self.btnEmpleados.clicked.connect(self.mdiArea.showFullScreen) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MenuPrincipal)

    def retranslateUi(self, MenuPrincipal):
        _translate = QtCore.QCoreApplication.translate
        MenuPrincipal.setWindowTitle(_translate("MenuPrincipal", "MainWindow"))
        self.btnUsuarios.setText(_translate("MenuPrincipal", "Usuarios"))
        self.btnEmpleados.setText(_translate("MenuPrincipal", "Empleados"))
        self.btnDepartamentos.setText(_translate("MenuPrincipal", "Departamentos"))
        self.btnBienes.setText(_translate("MenuPrincipal", "Bienes"))
        self.btnAsignacion.setText(_translate("MenuPrincipal", "Asignacion Bienes"))
        self.btnAlmacenamiento.setText(_translate("MenuPrincipal", "Almacenamiento"))
        self.btnReportes.setText(_translate("MenuPrincipal", "Reportes"))
        self.btnDesligar.setText(_translate("MenuPrincipal", "Desligar Bienes"))
        self.subwindow.setWindowTitle(_translate("MenuPrincipal", "Subwindow"))
        self.mniUsuarios.setText(_translate("MenuPrincipal", "Usuarios"))
        self.mniUsuarios.setToolTip(_translate("MenuPrincipal", "Usuarios"))
        self.mniEmpleados.setText(_translate("MenuPrincipal", "Empleados"))
        self.mniEmpleados.setToolTip(_translate("MenuPrincipal", "Emleados"))
import images_rc
