# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\paobe\Documents\proyecto_progra_2\Usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Usuarios(object):
    def setupUi(self, Usuarios):
        Usuarios.setObjectName("Usuarios")
        Usuarios.setEnabled(True)
        Usuarios.resize(628, 509)
        Usuarios.setMaximumSize(QtCore.QSize(628, 509))
        Usuarios.setStyleSheet("background-image: url(:/fondo/imagen-llamativa-cintas-sobre-fondo-oscuro-generacion-ai_724548-22165.jpg);")
        self.tablaUsuarios = QtWidgets.QTableWidget(Usuarios)
        self.tablaUsuarios.setGeometry(QtCore.QRect(10, 221, 601, 271))
        self.tablaUsuarios.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tablaUsuarios.setAccessibleName("")
        self.tablaUsuarios.setStyleSheet("background-color: rgb(139, 69, 0);")
        self.tablaUsuarios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablaUsuarios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablaUsuarios.setObjectName("tablaUsuarios")
        self.tablaUsuarios.setColumnCount(0)
        self.tablaUsuarios.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Usuarios)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 371, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAgregar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAgregar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"")
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout.addWidget(self.btnAgregar)
        self.btnEditar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnEditar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"\n"
"")
        self.btnEditar.setObjectName("btnEditar")
        self.horizontalLayout.addWidget(self.btnEditar)
        self.btnEliminar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnEliminar.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"")
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.btnCancelar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"    color: rgb(127, 0, 190);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid #ffffff;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color: rgb(255,255,255);\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"")
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.label_3 = QtWidgets.QLabel(Usuarios)
        self.label_3.setGeometry(QtCore.QRect(430, 10, 171, 181))
        self.label_3.setStyleSheet("image: url(:/fondo/perfil-de-usuario (1).png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(Usuarios)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 371, 96))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUsuarios = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblUsuarios.setEnabled(True)
        self.lblUsuarios.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblUsuarios.setObjectName("lblUsuarios")
        self.verticalLayout.addWidget(self.lblUsuarios)
        self.txtUsuario = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtUsuario.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtUsuario.setObjectName("txtUsuario")
        self.verticalLayout.addWidget(self.txtUsuario)
        self.lblContrasenia = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblContrasenia.setStyleSheet("QLabel{    \n"
"color:rgb(255,255,254);\n"
"font: 12pt\"Arial\";\n"
"background-color: rgb(170, 85, 0);;\n"
"}")
        self.lblContrasenia.setObjectName("lblContrasenia")
        self.verticalLayout.addWidget(self.lblContrasenia)
        self.txtContrasenia = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtContrasenia.setStyleSheet("QLineEdit{\n"
"/*background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"border:2px solid rgb(255,255,255);*/\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"color:rgb(255,255,254);\n"
"\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"/*background-color:rgba(0,0,0);\n"
"background-color: :rgba(12,12,12);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);*/\n"
"\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"/*color: rgb(255,255,255);*/\n"
"border:2px solid rgb(120,0,171);\n"
"  background-color: rgb(170, 85, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"background-color:rgba(0,0,0);\n"
"border-radius:10px;\n"
"font:12pt\"Arial\";\n"
"border:2px solid rgb(120,0,171);\n"
"}\n"
"")
        self.txtContrasenia.setObjectName("txtContrasenia")
        self.verticalLayout.addWidget(self.txtContrasenia)

        self.retranslateUi(Usuarios)
        QtCore.QMetaObject.connectSlotsByName(Usuarios)

    def retranslateUi(self, Usuarios):
        _translate = QtCore.QCoreApplication.translate
        Usuarios.setWindowTitle(_translate("Usuarios", "Form"))
        self.btnAgregar.setText(_translate("Usuarios", "Agregar"))
        self.btnEditar.setText(_translate("Usuarios", "Editar"))
        self.btnEliminar.setText(_translate("Usuarios", "Eliminar"))
        self.btnCancelar.setText(_translate("Usuarios", "Cancelar/Reintentar"))
        self.lblUsuarios.setText(_translate("Usuarios", "Usuario"))
        self.lblContrasenia.setText(_translate("Usuarios", "Contraseña"))
import images_rc
